
package presentacion;

/**
 *
 * @author Tom
 */
public class VistaSistema extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public VistaSistema() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        zonaPrincipal = new javax.swing.JPanel();
        panelTecnicos = new javax.swing.JScrollPane();
        infoTecnicos = new javax.swing.JTextArea();
        panelFacturas = new javax.swing.JScrollPane();
        listaFacturas = new javax.swing.JList<>();
        zonaBotones = new javax.swing.JPanel();
        botonFactura = new javax.swing.JButton();
        botonContratación = new javax.swing.JButton();
        botonSolicitarTecnico = new javax.swing.JButton();
        botonBajaContratación = new javax.swing.JButton();
        botonAltaTecnico = new javax.swing.JButton();
        botonNuevoAbonado = new javax.swing.JButton();
        botonNuevaFactura = new javax.swing.JButton();
        botonActualizarMes = new javax.swing.JButton();
        zonaRespuesta = new javax.swing.JPanel();
        panelRespuesta = new javax.swing.JScrollPane();
        respuesta = new javax.swing.JTextArea();
        comboAbonados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoTecnicos.setEditable(false);
        infoTecnicos.setColumns(20);
        infoTecnicos.setRows(5);
        panelTecnicos.setViewportView(infoTecnicos);

        listaFacturas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaFacturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        panelFacturas.setViewportView(listaFacturas);

        javax.swing.GroupLayout zonaPrincipalLayout = new javax.swing.GroupLayout(zonaPrincipal);
        zonaPrincipal.setLayout(zonaPrincipalLayout);
        zonaPrincipalLayout.setHorizontalGroup(
            zonaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaPrincipalLayout.createSequentialGroup()
                .addComponent(panelFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        zonaPrincipalLayout.setVerticalGroup(
            zonaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addComponent(panelFacturas)
        );

        zonaBotones.setPreferredSize(new java.awt.Dimension(113, 450));

        botonFactura.setText("Pagar Factura");
        botonFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonFacturaMouseClicked(evt);
            }
        });
        botonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturaActionPerformed(evt);
            }
        });

        botonContratación.setText("Nueva Contratación");
        botonContratación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonContrataciónMouseClicked(evt);
            }
        });

        botonSolicitarTecnico.setText("Solicitar Técnico");
        botonSolicitarTecnico.setActionCommand("");

        botonBajaContratación.setText("Baja Contratación");
        botonBajaContratación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBajaContrataciónMouseClicked(evt);
            }
        });

        botonAltaTecnico.setText("Alta Técnico");
        botonAltaTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAltaTecnicoMouseClicked(evt);
            }
        });

        botonNuevoAbonado.setText("Nuevo Abonado");
        botonNuevoAbonado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevoAbonadoMouseClicked(evt);
            }
        });

        botonNuevaFactura.setText("Nueva Factura");
        botonNuevaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevaFacturaMouseClicked(evt);
            }
        });

        botonActualizarMes.setText("Actualizar Mes");
        botonActualizarMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonActualizarMesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout zonaBotonesLayout = new javax.swing.GroupLayout(zonaBotones);
        zonaBotones.setLayout(zonaBotonesLayout);
        zonaBotonesLayout.setHorizontalGroup(
            zonaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonContratación, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
            .addComponent(botonBajaContratación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonSolicitarTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonActualizarMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonNuevaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonNuevoAbonado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonAltaTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        zonaBotonesLayout.setVerticalGroup(
            zonaBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zonaBotonesLayout.createSequentialGroup()
                .addComponent(botonBajaContratación, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(botonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(botonContratación, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSolicitarTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAltaTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonNuevoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonNuevaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonActualizarMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        respuesta.setEditable(false);
        respuesta.setColumns(20);
        respuesta.setRows(5);
        panelRespuesta.setViewportView(respuesta);

        javax.swing.GroupLayout zonaRespuestaLayout = new javax.swing.GroupLayout(zonaRespuesta);
        zonaRespuesta.setLayout(zonaRespuestaLayout);
        zonaRespuestaLayout.setHorizontalGroup(
            zonaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRespuesta)
        );
        zonaRespuestaLayout.setVerticalGroup(
            zonaRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        comboAbonados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAbonados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zonaRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zonaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zonaBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboAbonados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zonaBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zonaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(zonaRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void botonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFacturaActionPerformed

    private void botonFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonFacturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFacturaMouseClicked

    private void botonContrataciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContrataciónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonContrataciónMouseClicked

    private void botonBajaContrataciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBajaContrataciónMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBajaContrataciónMouseClicked

    private void botonAltaTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAltaTecnicoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAltaTecnicoMouseClicked

    private void botonNuevoAbonadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoAbonadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevoAbonadoMouseClicked

    private void botonNuevaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevaFacturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNuevaFacturaMouseClicked

    private void botonActualizarMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonActualizarMesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarMesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaSistema.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaSistema.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaSistema.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util
                .logging
                .Logger
                .getLogger(VistaSistema.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable() {
                public void run() {
                    new VistaSistema().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarMes;
    private javax.swing.JButton botonAltaTecnico;
    private javax.swing.JButton botonBajaContratación;
    private javax.swing.JButton botonContratación;
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton botonNuevaFactura;
    private javax.swing.JButton botonNuevoAbonado;
    private javax.swing.JButton botonSolicitarTecnico;
    private javax.swing.JComboBox<String> comboAbonados;
    private javax.swing.JTextArea infoTecnicos;
    private javax.swing.JList<String> listaFacturas;
    private javax.swing.JScrollPane panelFacturas;
    private javax.swing.JScrollPane panelRespuesta;
    private javax.swing.JScrollPane panelTecnicos;
    private javax.swing.JTextArea respuesta;
    private javax.swing.JPanel zonaBotones;
    private javax.swing.JPanel zonaPrincipal;
    private javax.swing.JPanel zonaRespuesta;
    // End of variables declaration//GEN-END:variables

}
